name: Build and push image
on:
  push:
    branches:
      - main
    paths:
      - image_inference/**
      - .github/workflows/build_image.yml

env:
  AWS_REGION: "eu-west-1" # Select this to suit where you'd like to deploy your workload
  ECR_REPOSITORY: mnist_inf # Name of ECR repo to hold custom Docker image
  OIDC_ROLE: arn:aws:iam::934765130326:role/github-actions-role # What role to assume in AWS
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  BuildPipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{env.OIDC_ROLE}}
          aws-region: ${{env.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to Amazon ECR # This is to be able to pull the SageMaker deep learning container, which sits in that account.
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: "763104351884"

      - name: build and push image to ECR
        working-directory: image_inference
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{env.ECR_REPOSITORY}}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest 
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
